soac_base/urls.py
from django.urls import path
from . import views

app_name = 'soac_base'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('features/', views.features, name="features"),

    #CRUD Function
    path('questions/', views.QuestionListView.as_view(), name="question-lists"),
    path('question/new/', views.QuestionCreateView.as_view(), name="question-create"),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name="question-detail"),
    path('questions/<int:pk>/update/', views.QuestionUpdateView.as_view(), name='question-update'),
    path('questions/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name='question-delete'),
    path('questions/<int:pk>/answer/', views.AnswerCreateView.as_view(), name='question-answer'),
    path('like/<int:pk>/', views.like_view, name="like_post")
]

stuck_on_a_concept/urls.py
from django.contrib import admin
from django.urls import path, include
from soac_users import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('soac_base.urls')),

    path('register/', user_view.register, name="register"),
    path('login/', auth_view.LoginView.as_view(template_name="soac_users/login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="soac_users/logout.html"), name='logout'), 
 
    # Profile system
    path('profile/', user_view.profile, name="profile"),
    path('profile/update/', user_view.profile_update, name="profile_update")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

soac_base/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Question(models.Model):
    """Question model map"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=10000)
    # content = models.TextField(null=True, blank=True)
    content = RichTextField()
    likes = models.ManyToManyField(User, related_name='question_post')
    date_create = models.DateTimeField(default=timezone.now)

    def __str__(self):
        """return a string format of the user and the relative question"""
        user_name = self.user.username
        return f'{user_name} - Question'

    def get_absolute_url(self):
        """interconnect the question url"""
        return reverse('soac_base:question-detail', kwargs={'pk':self.pk})

    def total_likes(self):
        """return a total likes on the relative question"""
        return self.likes.count()

class Answer(models.Model):
    """Question model map relative to Question"""
    question = models.ForeignKey(Question, related_name="answer", on_delete=models.CASCADE)
    name = models.CharField(max_length=1000)
    body = RichTextField()
    date_created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        """return the title of the question and it's user"""
        q_title = self.question.title
        q_user = self.question.user
        return f'{q_title} - {q_user}'

    def get_absolute_url(self):
        """return url"""
        return reverse('soac_base:question-detail', kwargs={'pk':self.pk})

    def save(self, *args, **kwargs):
        """ function that saves the instances """
        super().save(*args, **kwargs)

soac_base/forms.py
from .models import Answer
from django import forms
from ckeditor.widgets import CKEditorWidget

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())
    """
    class is a Django ModelForm that creates a form for the Comment
    widgets attribute, ensues they have the appropriate CSS
    classes ('form-control') for styling purposes.
    """
    class Meta:
        model = Answer
        fields = ['name', 'body']

        widgets = {
                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'body': forms.TextInput(attrs={'class': 'form-control'}),
                }

soac_base/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from .models import Question, Answer
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from .forms import CommentForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def features(request):
    return render(request, 'features.html')


@login_required
def like_view(request, pk):
    """ A function that allows users to post likes """
    post = get_object_or_404(Question, id=request.POST.get('question_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('soac_base:question-detail', args=[str(pk)]))

class QuestionListView(ListView):
    """ A class that list the recent questions based on Time """
    model = Question
    context_object_name = 'questions'
    ordering = ['-date_create']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ""
        if search_input:
            context['questions'] = context['questions'].filter(title__icontains = search_input)
            context['search_input'] = search_input
        return context

class QuestionDetailView(DetailView):
    """A class that url the question and readmore"""
    model = Question

    def get_context_data(self, *args, **kwargs):
        context = super(QuestionDetailView, self).get_context_data()
        something = get_object_or_404(Question, id=self.kwargs['pk'])
        total_likes = something.total_likes()
        liked = False
        if something.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['total_likes'] = total_likes
        context['liked'] = liked
        return context

class QuestionCreateView(LoginRequiredMixin, CreateView):
    """ A class that allows users to post questions """
    model = Question
    fields = ['title', 'content']
    context_object_name = 'questions'

    def form_valid(self, form):
        """ function that validates the form """
        form.instance.user = self.request.user
        return super().form_valid(form)

class QuestionUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    """ A class that permits users to update their questions """
    model = Question
    fields = ['title', 'content']
    permission_required = 'soac_base.change_question'

    def form_valid(self, form):
        """ function that validates the form"""
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        questions = self.get_object()
        if self.request.user == questions.user:
            return True
        return False
class QuestionDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    """ An instance that permits the rightful user to delete their question """
    model = Question
    context_object_name = 'question'
    success_url = "/questions"

    def test_func(self):
        questions = self.get_object()
        if self.request.user == questions.user:
            return True
        return False

class AnswerCreateView(LoginRequiredMixin,CreateView):
    """ A class that enable users to answer Questions """
    model = Answer
    form_class = CommentForm
    context_object_name =  'question'

    template_name = 'soac_base/question-answer.html'

    def form_valid(self, form):
        form.instance.question_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('soac_base:question-lists')

class AnswerDetailView(CreateView):
    """ A class that shows the details of the answer """
    model = Answer
    form_class = CommentForm

    templete_name = 'soac_base/question-detail.html'

    def form_valid(self, form):
        form.instance.question_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('soac_base:question-detail')

soac_base/templates/soac_base/question_detail.html
{% extends 'soac_base/questions-base.html' %}
{% block q_detail %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
           
            font-family: 'Poppins', sans-serif;
        }
        #fh1{
            margin-top: 20px;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: rgb(50, 122, 255);
        }
        /* .list-question{
            height: 400px;
            background-color: rgb(255, 219, 173);
        } */
        #fh3{
            text-align: center;
            font-size: 30px;
            text-align: left;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 17px;
                text-align: left;
            }
        }
        #fh6{
            text-align: left;
            font-size: 15px;
            /* padding-top: 20px; */
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: left;
                font-weight: normal;
            }
        }
        #fh5{
            display: flex;
            justify-content: space-around;
            text-align: left;
            font-size: 13px;
            padding-top: 3px;
            width: 90px;
            color: rgb(223, 223, 223);
            height: 20px;
            font-weight: normal;
            background-color: rgb(158, 158, 158);
            border-radius: 20px;
            /* padding-top: 20px; */
            /* background-color: blue; */
        }
        @media screen and (max-width: 600px) {
            #fh5{
                font-size: 10px;
            }
        }
        
    </style>
</head>
<body>
    <div class="container pt-5">
        <div class="list-question">
            <div class="questions">
                <div class="container" style="background-color: #D9D9D9; padding: 5px; box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 5px 0px; border-radius: 20px;" >
                    <h3 id="fh3">{{question.title}}</h3>
                    <hr>
                    <h6 id="fh6">{{ question.content|safe }}</h6>
                    <hr>
                    <div class="d-flex w-100 flex-row-reverse justify-content-between">
                        <h6 id="fh6" style="font-size: 10px; font-style: italic; color: #00000; text-align: right;">Asked By: <a href="{% url 'profile' %}" class="text-decoration-none">{{ object.user|title }} from {{ question.user.profile.city }} </a>&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp; On: {{ object.date_create|date:"j F, Y" }}</h6>
                        <br>
                            <form action="{% url 'soac_base:like_post' object.pk %}" method="POST">
                                {% csrf_token %}
                                {% if user.is_authenticated %}
                                    {% if liked %}
                                        <div style="display: flex; align-items: center;">
                                            <button type="submit" name="question_id" value="{{ question.id }}" style="border: none; border-radius: 60px;"><img src="https://image.similarpng.com/very-thumbnail/2020/06/Dislike-icon-transparent-PNG.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                                        </div>
                                    {% else %}
                                        <div style="display: flex; align-items: center;">
                                            <button type="submit" name="question_id" value="{{ question.id }}" style="border: none; border-radius: 30px;"><img src="https://i.pinimg.com/originals/39/44/6c/39446caa52f53369b92bc97253d2b2f1.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                                        </div>
                                    {% endif %}
                                {% else %}
                                    <h5 style="margin-left: 10px; cursor: pointer;"><a href="{% url 'login' %}">Login</a> to Like Question |  {{ total_likes }} Likes</h5>
                                {% endif %}
    
                            </form>
                    </div>
                    <br>
                    <h2>Answers...</h2> <br><br><br>

                    {% if not question.answer.all %}
                        <h3>No Answers yet... <a href="" class="text-decoration-none">Answer Question</a> </h3>
                    {% else %}
                        {% for answer in question.answer.all %}
                            <h3 style="font-weight: normal; font-size: 15px;">{{answer.body|safe}}</h3>
                            <h3 style="font-size: 10px;">Answered by: <i><a href="" class="text-decoration-none">{{answer.name}} from {{ question.user.profile.city }} </a> - On: {{answer.date_created|date:"j F, Y"}}</i></h3>
                            <hr>  
                        {% endfor %}
                    {% endif %}

                
                    
                    
                    <a class="btn btn-outline-primary" id="fa" href="{% url 'soac_base:question-answer' question.id %}" style="text-decoration: none;">Answer Question</a>
                    <a style="text-decoration: none; " class="btn btn-outline-success" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Edit Question" href="{% url 'soac_base:question-update' question.id %}">&#x270E;</a>
                    <a style="text-decoration: none; " class="btn btn-outline-danger" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Delete Question" href="{% url 'soac_base:question-delete' question.id %}">&#x2716;</a>
                    <a style="text-decoration: none; " class="btn btn-outline-secondary" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Go Back" href="{% url 'soac_base:question-lists' %}">&#x21a9;</a>
                </div> <br><br>
                
                </div> <br>
            </div>
        </div>
        <br>
        
    </div>
</body>
</html>
{% endblock q_detail %}

soac_base/templates/soac_base/question_list.html
{% extends 'soac_base/questions-base.html' %}
{% load static %}
{% block question-list %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{

            font-family: 'Poppins', sans-serif;
        }
        .sidebar {
            flex: 1 1 10%;
            min-height: 100vh;
            background-color: #001848;
          
        }
        #sidebar_list {
            height: 85%;
        }
        .main-content {
            flex: 1 0 80%;
            padding: 20px;
        }
 
        .infinite-scroll-container {
            height: 500px; /* Set the fixed height */
            overflow-y: auto; /* Enable vertical scrolling */
            border: 1px solid #ccc; /* Optional: for visual purposes */
            padding: 10px;
        }

        @media screen and (min-width: 522px) {
            #sidebar_list {
                height: 45%;
            }
        }
    </style>
</head>
<body>
    <div class="d-flex flex-wrap">
        <div class="sidebar pt-2">
            <ul class="nav flex-column align-items-center justify-content-evenly" id="sidebar_list">
                <li class="nav-item">
                    <a class="nav-link active text-white" href="#" id="link1">
                        <i class="bi bi-house"></i>
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="#" id="link2">
                        <i class="bi bi-question-circle"></i>
                        Questions
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="#" id="link3">
                        <i class="bi bi-tags-fill"></i>
                       Tags
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="#" id="link4">
                        <i class="bi bi-bookmark-heart-fill"></i>
                       Saves
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="#" id="link5">
                        <i class="bi bi-star-fill"></i>
                        Rewards
                    </a>
                </li>
            </ul>
        </div>
        <div class="main-content">
            <div id="content1" class="list-question">
                <div class="d-flex justify-content-between mb-4">
                    <h4 class="mb-0 fs-5">Top Questions</h4>
                    <a class="btn text-white" href="{% url 'soac_base:question-create' %}" style="background-color: #4472C4;">Ask Question</a>
                </div>
                <div class="questions infinite-scroll-container" >
                    {% for question in questions %}
                    <div class="container border border-2 border-black rounded-3" style="background: linear-gradient(to right, rgb(217, 217, 217), rgba(217, 217, 217); padding: 5px; box-shadow: rgba(0, 0, 0, 0.383) 0px 5px 5px 0px; border-radius: 15px;" >
                        <div id="title-sec" style="display: flex; align-items: center;">

                            <h3 id="fh3"><a href="{% url 'soac_base:question-detail' question.id %}">{{ question.title }}</a></h3>
                        </div>
                        
                        {% if question.content|wordcount <= 10 %}
                        <h6 id="fh6" style="text-align: left;">{{ question.content}}</h6>
                        {% else %}
                        <h6 id="fh6" style="text-align: left;">{{ question.content|truncatewords:10}} <a href="{% url 'soac_base:question-detail' question.id %}">Read More</a></h6>
                        {% endif %}
                        <h6 id="fh6" class="" style="font-size: 10px; font-style: italic; color: black;">Asked By: <a class="text-decoration-none" href="">{{ question.user }} from {{ question.user.profile.city }} </a>&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp; On: {{question.date_create|date:"j F, Y"}}</h6>
                        <h5 style="text-align: right; font-size: 12px; font-style: italic;">Tags</h5>
                    </div> <br>
                    
                    {% endfor %}
                </div>
            </div>
            <div id="content2" style="display: none;">
                <div>
                    <h1>Welcome to View 2</h1>                                                                                                                                                                                                                                                                                                                                                                                                                                        
                    <p>Feature in development.</p>
                </div>

            </div>
            <div id="content3" style="display: none;">
                <h1>Welcome to View 3</h1>
                <p>Feature in development.</p>
            </div>
            <div id="content4" style="display: none;">
                <h1>Welcome to View 4</h1>
                <p>Feature in development.</p>
            </div>
            <div id="content5" style="display: none;">
                <h1>Welcome to View 5</h1>
                <p>Feature in development.</p>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock question-list %}

soac_base/templates/soac_base/questions-base.html
{% load static %}
{% load cloudinary %}
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>Stuck-On-A-Concept</title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.2/font/bootstrap-icons.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static "main.css" %}"/>
        <link rel="stylesheet" href="{% static 'ckeditor/ckeditor.css' %}">
        <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
        <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    </head>
    <body>
        {% block navbar1 %}
<header>
    <nav class="navbar navbar-expand-xl navbar-light bg-white" style="border-bottom: 0.1rem solid #D9D9D9;">
        <div class="container">
          <div id="nav_logo_div">
            <img src="{% static 'images/logo.jpeg' %}" id="nav_logo">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'soac_base:question-lists' %}" style="margin-right: 0px;">stuck-on-a-concept</a>
            {% else %}
            <a class="navbar-brand" href="{% url 'soac_base:home' %}" style="margin-right: 0px;">stuck-on-a-concept</a>
            {% endif %}
          </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" id="burger_icon">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse ms-lg-3 justify-content-between" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0 w-25 d-flex justify-content-between">
              {% if user.is_authenticated%}
              <li class="nav-item">
                <a class="nav-link" href="#">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">For Teams</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Q&A</a>
              </li>
              {% endif %}
            </ul>
            <form class="d-flex justify-content-between w-50" method="GET">
              <input type="search" placeholder="Search..." aria-label="Search" name="search-area" style="width: 80%;">
              <button type="submit" style="border-radius: 25px; border: none; padding: 8px;">Search</button>
            </form>
            <div class="d-flex justify-content-between" style="width: 17%;">
              {% if user.is_authenticated %}
              <a href="{% url 'profile' %}" class="btn"  type="submit" style="color: #4472C4; border-color: #4472C4">Profile</a>
              <a href="{% url 'logout' %}" class="btn text-white" type="submit" style="background-color: #4472C4;">Logout</a>
          {% else %}
          <a href="{% url 'login' %}" class="btn" type="submit" style="color: #4472C4; border-color: #4472C4">Login</a>
          <a href="{% url 'register' %}" class="btn text-white" type="submit" style="background-color: #4472C4;">Sign up</a>
          {% endif %}

            </div>
          </div>
        </div>
      </nav>
      {% if messages %}
      <div id="message_container">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}" role="alert">
            <h4 style="text-align: center;">{{ message }}</h4>
          </div>
        {% endfor %}
      </div>
      {% endif %}

 </header>

 {% endblock navbar1 %}

 {% block question-list %}

 {% endblock question-list %}

 {% block content %}

 {% endblock content %}

 {% block prof_update %}

 {% endblock prof_update %}

 {% block q_detail %}

 {% endblock q_detail %}

 {% block question_form %}

 {% endblock question_form %}

 {% block q_conf_del %}

 {% endblock q_conf_del %}

 {% block q_answer %}

 {% endblock q_answer %}


{% block footer1 %}
<footer class="py-5 bg-dark">
    <div class="container">
        <div class="row">
            <div class="custom-col-5">
                <h6 class="text-white footer_title">STUCK-ON-A-CONCEPT</h6>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-white text-decoration-none footer_item">Questions</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item" >Help</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Join</a></li>
                </ul>
            </div>
            <div class="custom-col-5">
                <h6 class="text-white footer_title">PRODUCTS</h6>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-white text-decoration-none footer_item">Teams</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Advertising</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Collectives</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Talent</a></li>
                </ul>
            </div>
            <div class="custom-col-5">
                <h6 class="text-white footer_title">COMPANY</h6>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-white text-decoration-none footer_item">About</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Press</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Work here</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Legal</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item" >Privacy policy</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Contact us</a></li>
                </ul>
            </div>
            <div class="custom-col-5">
                <h6 class="text-white footer_title">EXCHANGE NETWORKS</h6>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-white text-decoration-none footer_item">Technology</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item ">Life/Arts</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Culture</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Science</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Other</a></li>
                </ul>
            </div>
            <div class="custom-col-5">
                <ul class="list-unstyled w-100 social_links">
                    <li><a href="#" class="text-white text-decoration-none footer_item">Blog</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Facebook</a></li>
                    <li><a href="#" class="text-white text-decoration-none footer_item">Twitter</a></li>
                </ul>
            </div>
        </div>
        <div class="d-flex justify-content-center align-items-center">
            <p style="margin: 3px 0px;" class="text-white text-center">© 2024 Stuck-On-A-Concept contributions</p>
        </div>
    </div>

  </footer>
{% endblock footer1 %}

        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
            const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
            
            $('.nav-link').on('click', function(e) {
                e.preventDefault();
                $('.nav-link').removeClass('active');
                $(this).addClass('active');
                var id = $(this).attr('id');
                $('.main-content > div').hide();
                $('#content' + id.substr(4)).show();
            });
        });
    </script>
    </body>
</html>