soac_base/urls.py
from django.urls import path
from . import views

app_name = 'soac_base'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('features/', views.features, name="features"),

    #CRUD Function
    path('questions/', views.QuestionListView.as_view(), name="question-lists"),
    path('question/new/', views.QuestionCreateView.as_view(), name="question-create"),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name="question-detail"),
    path('questions/<int:pk>/update/', views.QuestionUpdateView.as_view(), name='question-update'),
    path('questions/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name='question-delete'),
    path('questions/<int:pk>/answer/', views.AnswerCreateView.as_view(), name='question-answer'),
    path('like/<int:pk>/', views.like_view, name="like_post")
]

stuck_on_a_concept/urls.py
from django.contrib import admin
from django.urls import path, include
from soac_users import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('soac_base.urls')),

    path('register/', user_view.register, name="register"),
    path('login/', auth_view.LoginView.as_view(template_name="soac_users/login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="soac_users/logout.html"), name='logout'), 
 
    # Profile system
    path('profile/', user_view.profile, name="profile"),
    path('profile/update/', user_view.profile_update, name="profile_update")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/about.html
{% extends 'base.html' %} {% load static %} {% block about %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      @import url("https://fonts.googleapis.com/css?family=Poppins");
      body {
        background-color: #ffff;
      }
      a {
        color: black;
      }
      a:focus {
        color: black;
      }
      a:hover {
        color: black;
      }
      .story_container {
        height: 100%%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
      }
      .story_container div:first-child {
        margin-bottom: 20px;
      }
      .story_container div:nth-child(2) {
        margin-bottom: 25px;
      }
      .paragraph_container p {
        margin-bottom: 0rem;
        text-align: center;
      }

      .padding {
        padding: 4rem 0rem;
      }
      .team_container {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height: 700px;
      }
      .team_member {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
        border-radius: 5px;
        -webkit-box-shadow: 0 0 10px rgba(128, 128, 128, 0.5);
        box-shadow: 0 0 10px rgba(128, 128, 128, 0.5);
        height: 220px;
      }
      .team_member_socials {
        display: flex;
        justify-content: space-between;
      }
      .repo {
        display: flex;
        margin-top: 20px;
        justify-content: center;
      }

      .user-card-full {
        overflow: hidden;
      }

      .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        box-shadow: 0 1px 20px 0 rgba(53, 53, 53, 0.452);
        border: none;
        margin-bottom: 30px;
      }

      .bg-c-lite-green {
        background-color: #001848;
      }

      @media only screen and (min-width: 576px) {
        .paragraph_container p {
          text-align: left;
        }
        .team_container {
          display: flex;
          flex-direction: row;
          justify-content: space-between;
          height: 225px;
        }
        .team_member {
          width: 30%;
        }
      }
      @media only screen and (min-width: 492px) {
        #question_btns {
          width: 75%;
        }
      }
    </style>
  </head>
  <body>
    <div class="page-content page-container" id="page-content">
      <div class="padding">
        <div class="row d-flex justify-content-center">
          <div class="col-xl-8 col-md-8 card p-4">
            <div class="user-card-full">
              <h1 class="text-center">Our story...</h1>
              <div class="story_container">
                <div class="paragraph_container">
                  <p>
                    Our team, composed of passionate learners from the ALX
                    Software Engineering program, experienced firsthand the
                    frustrations of coding challenges. We often found ourselves
                    stuck on complex problems, spending countless hours
                    searching for solutions online, and feeling overwhelmed by
                    the lack of accessible guidance. These struggles highlighted
                    the need for a platform that could provide timely, reliable
                    support tailored specifically for students like us.
                  </p>
                </div>
                <div class="paragraph_container">
                  <p>
                    One pivotal moment that inspired us was when one of the team
                    members, encountered a baffling error during an intense
                    project. Despite his best efforts, he couldn’t solve it
                    alone. Reaching out to a peer, they collaborated and finally
                    found the solution together. This experience underscored the
                    importance of community and accessible help, sparking the
                    idea for Stuck-on-a-Concept: a learning app designed to
                    offer real-time assistance, collaborative learning
                    opportunities, and a supportive community.
                  </p>
                </div>
                <div class="paragraph_container">
                  <p>
                    Stuck-on-a-Concept aims to transform the learning experience
                    for ALX students by providing immediate help with coding
                    problems, connecting learners with peers and mentors, and
                    offering a wealth of accessible resources. Our vision is to
                    foster an empowered community of future software engineers
                    who can overcome obstacles, build confidence, and achieve
                    their dreams without being hindered by avoidable
                    frustrations. Join us, and let’s solve these challenges
                    together.
                  </p>
                </div>
              </div>
              <div class="mt-5 px-4">
                <h1 class="text-center">The Team</h1>

                <div class="team_container">
                  <div class="team_member py-4">
                    <img src="{% static "images/VUYISILE-min.png"%}"
                    class="rounded-circle img-fluid" style="height: 100px;
                    width: 100px;"/>
                    <h6>Vuyisile Lehola</h6>
                    <div class="team_member_socials xs: w-50 md: w-75">
                      <a href="https://x.com/vt_lehola" target="blank"
                        ><i class="bi bi-twitter"></i
                      ></a>
                      <a
                        href="https://www.linkedin.com/in/vuyisile-lehola-99a597122/"
                        target="blank"
                        ><i class="bi bi-linkedin"></i
                      ></a>
                      <a href="https://github.com/vtl-28" target="blank"
                        ><i class="bi bi-github"></i
                      ></a>
                    </div>
                  </div>
                  <div class="team_member py-4">
                    <img src="{% static "images/COMFORT-min.png"%}"
                    class="rounded-circle img-fluid" style="height: 100px;
                    width: 100px;"/>
                    <h6>Comfort Shingange</h6>
                    <div class="team_member_socials xs: w-50 md: w-75">
                      <a href="https://x.com/ComfortShingan1" target="blank"
                        ><i class="bi bi-twitter"></i
                      ></a>
                      <a
                        href="https://www.linkedin.com/in/comfort-shingange-ab4446250/"
                        target="blank"
                        ><i class="bi bi-linkedin"></i
                      ></a>
                      <a href="https://github.com/Comfort99" target="blank"
                        ><i class="bi bi-github"></i
                      ></a>
                    </div>
                  </div>
                  <div class="team_member py-4">
                    <img src="{% static "images/SADIKADAMS-min.png"%}"
                    class="rounded-circle img-fluid" style="height: 100px;
                    width: 100px;"/>
                    <h6>Sadik Adams</h6>
                    <div class="team_member_socials xs: w-50 md: w-75">
                      <a href="https://x.com/najultinti" target="blank"
                        ><i class="bi bi-twitter"></i
                      ></a>
                      <a
                        href="https://www.linkedin.com/in/adams-sadik-inspires/"
                        target="blank"
                        ><i class="bi bi-linkedin"></i
                      ></a>
                      <a href="https://github.com/PoisebTechHub" target="blank"
                        ><i class="bi bi-github"></i
                      ></a>
                    </div>
                  </div>
                </div>
                <div class="repo">
                  <a
                    href="https://github.com/vtl-28/stuck-on-a-concept"
                    target="blank"
                    class="ms-1 text-decoration-none"
                    ><span class="fw-bold">Project Github repository: </span>
                    https://github.com/vtl-28/stuck-on-a-concept</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
{% endblock about %}

templates/base.html
{% load compress %}
{% load static %}
{% load cloudinary %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Stuck-On-A-Concept</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'main.css' %}" />
        <link rel="stylesheet" href="{% static "anime.css" %}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.2/font/bootstrap-icons.min.css" rel="stylesheet">
        {% compress css %}
        <link type="text/x-scss" rel="stylesheet" href="{% static 'scss/bootstrap.scss' media="screen" %}">
        {% endcompress %}
    </head>
    <body>
        {% block navbar %}
        <header>
            <nav class="navbar navbar-expand-xl navbar-light bg-white" style="border-bottom: 0.1rem solid #D9D9D9;">
                <div class="container">
                  <div id="nav_logo_div">
                    <img src="{% static 'images/logo.jpeg' %}" id="nav_logo">
                    <a class="navbar-brand" href="{% url 'soac_base:home' %}" style="margin-right: 0px;">stuck-on-a-concept</a>
                  </div>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" id="burger_icon">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse ms-xl-5" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0 w-25 d-flex justify-content-between">
                      {% if user.is_authenticated%}
                      <li class="nav-item">
                        <a class="nav-link" href="#">Products</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#">For Teams</a>
                      </li>
                      {% else %}
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'soac_base:about' %}">About</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'soac_base:features' %}">Feature</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#">Q&A</a>
                      </li>
                      {% endif %}
                    </ul>
                    <form class="d-flex flex-sm-column flex-xs-column flex-md-column flex-lg-row ms-xl-5 justify-content-between w-75">
                      <input type="search" placeholder="Search" aria-label="Search" id="search_input">
                      <div class="d-flex justify-content-between" id="nav_btns">
                        {% if user.is_authenticated %}
                        <a href="{% url 'profile' %}" class="btn" type="submit" style="color: #4472C4; border-color: #4472C4">Profile</a>
                        <a href="{% url 'logout' %}" class="btn text-white" type="submit" style="background-color: #4472C4;">Logout</a>
                    {% else %}
                    <a href="{% url 'login' %}" class="btn" type="submit" style="color: #4472C4; border-color: #4472C4">Login</a>
                    <a href="{% url 'register' %}" class="btn text-white" type="submit" style="background-color: #4472C4;">Sign up</a>
                    {% endif %}
        
                      </div>
                    </form>
                  </div>
                </div>
              </nav>
              {% if messages %}
              <div id="message_container">
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}" role="alert">
                    <h4 style="text-align: center;">{{ message }}</h4>
                  </div>
                {% endfor %}
              </div>
              {% endif %}
        
            </div>
            
         </header>
        
        {% endblock navbar %}

          {% block content %}

        {% endblock content %}
        {% block about %}

 {% endblock about %}
 {% block features %}

 {% endblock features %}
        {% block landing_page %}

        {% endblock landing_page %}
        {% block register %}

        {% endblock register %}
     
          {% block footer %}
          <footer class="py-5 bg-dark">
            <div class="container">
                <div class="row">
                    <div class="custom-col-5">
                        <h6 class="text-white footer_title">STUCK-ON-A-CONCEPT</h6>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white text-decoration-none footer_item">Questions</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item" >Help</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Join</a></li>
                        </ul>
                    </div>
                    <div class="custom-col-5">
                        <h6 class="text-white footer_title">PRODUCTS</h6>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white text-decoration-none footer_item">Teams</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Advertising</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Collectives</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Talent</a></li>
                        </ul>
                    </div>
                    <div class="custom-col-5">
                        <h6 class="text-white footer_title">COMPANY</h6>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white text-decoration-none footer_item">About</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Press</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Work here</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Legal</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item" >Privacy policy</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Contact us</a></li>
                        </ul>
                    </div>
                    <div class="custom-col-5">
                        <h6 class="text-white footer_title">EXCHANGE NETWORKS</h6>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white text-decoration-none footer_item">Technology</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item ">Life/Arts</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Culture</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Science</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Other</a></li>
                        </ul>
                    </div>
                    <div class="custom-col-5">
                        <ul class="list-unstyled w-100 social_links">
                            <li><a href="#" class="text-white text-decoration-none footer_item">Blog</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Facebook</a></li>
                            <li><a href="#" class="text-white text-decoration-none footer_item">Twitter</a></li>
                        </ul>
                    </div>
                </div>
                <div class="d-flex justify-content-center align-items-center">
                    <p style="margin: 3px 0px;" class="text-white text-center">© 2024 Stuck-On-A-Concept contributions</p>
                </div>
            </div>
          
        </footer>
          {% endblock footer %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

templates/features.html
{% extends 'base.html' %} {% load static %} {% block features %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins');
        body {
          background-color: #ffff
          /* background: linear-gradient(230deg, orange 0%, yellow 100%); */

      }
      .team_container {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height: 700px;

      }
      .team_member {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
        border-radius: 5px;
        -webkit-box-shadow: 0 0 10px rgba(128, 128, 128, 0.5);
        box-shadow: 0 0 10px rgba(128, 128, 128, 0.5);
        height: 220px;
      }
      .team_member_socials {
        display: flex;
        justify-content: space-between;

      }
      @media only screen and (min-width: 576px) {
        .paragraph_container p {
          text-align: left;
        }
        .team_container {
          display: flex;
          flex-direction: row;
          justify-content: space-between;
          height: 225px;

        }
        .team_member {
         width: 30%;

        }
        .feature_text {
            font-size: 12px;
        }
    }
    @media only screen and (min-width: 992px) {
        .feature_text {
            font-size: 13px;
        }
    }

      .padding {
          padding: 4rem 0rem;
      }

      .user-card-full {
          overflow: hidden
      }

      .card {
          border-radius: 5px;
          -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
          box-shadow: 0 1px 20px 0 rgba(53, 53, 53, 0.452);
          border: none;
          margin-bottom: 30px
      }

      .bg-c-lite-green {
          background-color: #001848;
      }

      #question_btns {
          width: 100%;
      }
      @media only screen and (min-width: 492px) {
          #question_btns {
              width: 75%;
          }
      }
     

      @media only screen and (min-width: 1400px) {
          p {
              font-size: 14px
          }
      }

      .user-card-full .social-link li {
          display: inline-block
      }

      .user-card-full .social-link li a {
          font-size: 20px;
          margin: 0 10px 0 0;
          -webkit-transition: all 0.3s ease-in-out;
          transition: all 0.3s ease-in-out
      }
    </style>
  </head>
  <body>
    <div class="page-content page-container" id="page-content">
      <div class="padding">
        <div class="row d-flex justify-content-center">
          <div class="col-xl-8 col-md-8 card p-4">
            <div class="user-card-full">
              <h4 class="text-center">stuck-on-a-concept offers these amazing key features</h4>
              </div>
              <div class="mt-4 px-4">
                <div class="team_container">
                  <div class="team_member py-4 px-2">
                    <img src="{% static "images/solutiontoproblems.png"%}"
                    class="rounded-circle img-fluid" style="height: 100px;
                    width: 100px;"/>
                    <h6 class="mt-2 fw-bold">Coding Challenges</h6>
                    <div class="feature_description">
                        <p class="text-center feature_text">Get assistance and solutions to coding challenges</p>
                    </div>
                  </div>
                  <div class="team_member py-4 px-2">
                    <img src="{% static "images/rewardd-min.jpg"%}"
                    class="rounded-circle img-fluid" style="height: 100px;
                    width: 100px;"/>
                    <h6 class="mt-2 fw-bold">Rewards</h6>
                    <div class="feature_description">
                        <p class="text-center feature_text">Get rewarded for making valuable contributions towards assisting other students</p>
                    </div>
                  </div>
                  <div class="team_member py-4 px-2">
                    <img src="{% static "images/sharingideas.jpg"%}"
                    class="rounded-circle img-fluid" style="height: 100px;
                    width: 100px;"/>
                    <h6 class="mt-2 fw-bold">Team Collaboration</h6>
                    <div class="feature_description">
                        <p class="text-center feature_text">Network and build relationships with like-minded people</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
{% endblock features %}