soac_base/urls.py
from django.urls import path
from . import views

app_name = 'soac_base'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('features/', views.features, name="features"),

    #CRUD Function
    path('questions/', views.QuestionListView.as_view(), name="question-lists"),
    path('question/new/', views.QuestionCreateView.as_view(), name="question-create"),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name="question-detail"),
    path('questions/<int:pk>/update/', views.QuestionUpdateView.as_view(), name='question-update'),
    path('questions/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name='question-delete'),
    path('questions/<int:pk>/answer/', views.AnswerCreateView.as_view(), name='question-answer'),
    path('like/<int:pk>/', views.like_view, name="like_post")
]

stuck_on_a_concept/urls.py
from django.contrib import admin
from django.urls import path, include
from soac_users import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('soac_base.urls')),

    path('register/', user_view.register, name="register"),
    path('login/', auth_view.LoginView.as_view(template_name="soac_users/login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="soac_users/logout.html"), name='logout'), 
 
    # Profile system
    path('profile/', user_view.profile, name="profile"),
    path('profile/update/', user_view.profile_update, name="profile_update")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

soac_users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from cloudinary.models import CloudinaryField


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=1000, blank=True)
    city = models.CharField(max_length=100, blank=True, default="Johannesburg")
    image = CloudinaryField('image', default='https://res.cloudinary.com/dd1jqwp94/image/upload/v1720597929/default_dktxl8.jpg', transformation={"width": 300, "height": 300, "crop": "limit"})

    def __str__(self):
        return f'{self.user.username} - Profile'

soac_users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.db.models import fields
from .models import Profile
from cloudinary.forms import CloudinaryFileField

class UserRegisterForm(UserCreationForm):
    email = models.EmailField()
    city = forms.CharField(max_length=100, required=False)

    class Meta:
        model = User
        fields = '__all__'


    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
       
        ordered_fields = ['username', 'email', 'city', 'password1', 'password2']
        self.fields = {k: self.fields[k] for k in ordered_fields if k in self.fields}
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            profile = Profile(user=user, city=self.cleaned_data['city'])  # Save the city in Profile
            profile.save()
        return user


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    image = CloudinaryFileField()
    class Meta:
        model = Profile
        fields = ['bio', 'city', 'image']

soac_users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
from .forms import ProfileUpdateForm, UserUpdateForm

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Successfully created for {username}! Login In Now')
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'soac_users/register.html', {'form': form})

@login_required
def profile(request):
        return render(request, 'soac_users/profile.html')


@login_required
def profile_update(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account Updated Successfully!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'soac_users/profile_update.html', context)

soac_users/templates/soac_users/login.html
{% extends 'base.html' %} {% load crispy_forms_tags %} 
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div class="wrapper fadeInDown">
      <div id="formContent" class="pt-3">
        <h2 class="active">
          <a class="signin" href="" style="text-decoration: none">Sign In</a>
        </h2>
        <h2 class="inactive underlineHover">
          <a class="signin" href="{% url 'register' %}" style="text-decoration: none"
            >Sign Up</a
          >
        </h2>
        <div class="fadeIn first"></div>
        <form action="" method="POST">
          {% csrf_token %} {{form|crispy}}
          <input type="submit" class="fadeIn fourth" value="Sign In" />
        </form>

        <div id="formFooter">
          <p>
            Don't have an account yet?
            <a class="underlineHover" href="{% url 'register' %}">Register </a>
          </p>
        </div>
      </div>
    </div>
  </body>
</html>
{% endblock content %}

soac_users/templates/soac_users/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">

        <title>Logout Page</title>
        <style>
            body{
                background: linear-gradient(230deg, #001848 0%, #001848 100%);

            }
            .containerr{
                margin-top: 100px;
                margin-bottom: 130px;

            }
            #logoutid1{
                text-align: center;
                font-size: 30px;
                color: white;
                font-weight: 600;
                font-family: 'Poppins', sans-serif;
            }
            #logout-btn{
                text-align: center;
                margin: auto;
                display: flex;
                justify-self: center;
            }
            #fa{
                color: black;
                text-decoration: none;
            }
        </style>
    </head>
    <body>
        <div class="containerr">
            <h3 id="logoutid1">You have been logged out!!</h3>
            <div>
                <button class="btn bg-white" id="logout-btn"><a id="fa" href="{% url 'login' %}">LOGIN</a></button>

            </div>
        </div>
    </body>
    </html>
    {% endblock content %}

soac_users/templates/soac_users/profile.html
{% extends 'soac_base/questions-base.html' %}
{% load crispy_forms_tags %}
{% block prof_update %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <script src="https://unpkg.com/feather-icons"></script>
        {% comment %} <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet"> {% endcomment %}

        <style>
            body {
            background-color: #ffff
            /* background: linear-gradient(230deg, orange 0%, yellow 100%); */

        }

        .padding {
            padding: 4rem 0rem;
        }

        .user-card-full {
            overflow: hidden
        }

        .card {
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
            box-shadow: 0 1px 20px 0 rgba(53, 53, 53, 0.452);
            border: none;
            margin-bottom: 30px
        }

        .m-r-0 {
            margin-right: 0px
        }

        .m-l-0 {
            margin-left: 0px
        }

        .user-card-full .user-profile {
            border-radius: 5px 0 0 5px
        }

        .bg-c-lite-green {
            {% comment %} background: -webkit-gradient(linear, left top, right top, from(#001848), to(#001848));
            background: linear-gradient(to right, rgb(0, 24, 72), blue) {% endcomment %}
            background-color: #001848;
        }

        .user-profile {
            padding: 20px 0
        }

        .card-block {
            padding: 1.25rem
        }

        .m-b-25 {
            margin-bottom: 25px
        }

        .img-radius {
            border-radius: 100px
        }
        @media only screen and (min-width: 1400px) {
            .img-radius {
            border-radius: 100px
        }
        }
        h6 {
            font-size: 13px;
            font-family: 'Poppins', sans-serif;

        }

        .card .card-block p {
            line-height: 25px
        }

        @media only screen and (min-width: 1400px) {
            p {
                font-size: 14px
            }
        }

        .card-block {
            padding: 1.25rem
        }

        .b-b-default {
            border-bottom: 1px solid #e0e0e0
        }

        .m-b-20 {
            margin-bottom: 20px
        }

        .p-b-5 {
            padding-bottom: 5px !important
        }

        .card .card-block p {
            line-height: 25px
        }

        .m-b-10 {
            margin-bottom: 10px
        }

        .text-muted {
            color: #919aa3 !important
        }

        .b-b-default {
            border-bottom: 1px solid #e0e0e0
        }

        .f-w-600 {
            font-weight: 600
        }

        .m-b-20 {
            margin-bottom: 20px
        }

        .m-t-40 {
            margin-top: 20px
        }

        .p-b-5 {
            padding-bottom: 5px !important
        }

        .m-b-10 {
            margin-bottom: 10px
        }

        .m-t-40 {
            margin-top: 20px
        }

        .user-card-full .social-link li {
            display: inline-block
        }

        .user-card-full .social-link li a {
            font-size: 20px;
            margin: 0 10px 0 0;
            -webkit-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out
        }
        </style>
    </head>
    <body>
        <div class="page-content page-container" id="page-content">
            <div class="padding">
                <div class="row  d-flex justify-content-center">
                    <div class="col-xl-6 col-md-12 card p-4" >
                        <div class="user-card-full">
                            <div class="row m-l-0 m-r-0">
                                <div class="col-sm-4 bg-c-lite-green user-profile">
                                    <div class="card-block text-center text-white">
                                        <div class="m-b-25"> 
                                            {% comment %} {% load cloudinary %}
                                            {% cloudinary user.profile.image.url quality='auto' width=300 height=300 crop='pad' background='gen_fill:ignore-foreground_true' %} {% endcomment %}
                                            <img src="{{ user.profile.image.url }}" class="img-radius img-fluid" alt="User-Profile-Image">
                                        </div>
                                        <h6 class="f-w-600" style="font-size: 24px; color: white;">{{ user.username|title }}</h6>
                                        <p style="font-size: 14px; color: white;">{{ user.profile.bio|title }}</p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                                        <div style="margin-top: 10px;">
                                            <button class="btn bg-white" id="logout-btn"><a id="fa" href="{% url 'profile_update' %}" style="color: black; text-decoration: none;">Update Profile</a></button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-8">
                                    <div class="card-block">
                                        <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Profile Information</h6>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <p class="m-b-10 f-w-600">Email</p>
                                                <h6 class="text-muted f-w-400">{{ user.email }}</h6>
                                            </div>
                                            <div class="col-sm-6">
                                                <p class="m-b-10 f-w-600">Location</p>
                                                <h6 class="text-muted f-w-400">{{ user.profile.city|title }}</h6>
                                            </div>
                                        </div>
                                        <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Projects</h6>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <p class="m-b-10 f-w-600">Recent</p>
                                                <h6 class="text-muted f-w-400"><a href="#">Project1</a></h6>
                                            </div>
                                            <div class="col-sm-6">
                                                <p class="m-b-10 f-w-600">Most Viewed</p>
                                                <h6 class="text-muted f-w-400"><a href="#">Project2</a></h6>
                                            </div>
                                            <div style="margin-top: 55px;">
                                                <button class="btn btn-secondary" id="logout-btn"><a id="fa" href="{% url 'soac_base:question-create' %}" style="color: white; text-decoration: none;">Ask Question</a></button>
                                                <button class="btn btn-outline-primary" id="logout-btn"><a id="fa" href="{% url 'soac_base:question-lists' %}" style="color: rgb(0, 0, 0); text-decoration: none;">View Questions</a></button>
                                            </div>
                                        </div>
                                        
                                        
                                        <ul class="social-link list-unstyled m-t-40 m-b-10">
                                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook" data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook" aria-hidden="true"></i></a></li>
                                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter" data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter" aria-hidden="true"></i></a></li>
                                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="instagram" data-abc="true"><i class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            feather.replace()
          </script>
    </body>
    </html>     
{% endblock prof_update %}

soac_users/templates/soac_users/profile_update.html
{% extends 'soac_base/questions-base.html' %}
{% load crispy_forms_tags %}
{% block prof_update %}  
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    {% comment %} <script src="https://unpkg.com/feather-icons"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet"> {% endcomment %}

    <style>
    {% comment %} body {
        background-color: #ffff
        /* background: linear-gradient(230deg, orange 0%, yellow 100%); */

    } {% endcomment %}

    .padding {
        padding: 4rem 0rem;
    }

    .user-card-full {
        overflow: hidden
    }

    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        box-shadow: 0 1px 20px 0 rgba(53, 53, 53, 0.452);
        border: none;
        margin-bottom: 30px
    }

    .m-r-0 {
        margin-right: 0px
    }

    .m-l-0 {
        margin-left: 0px
    }

    .user-card-full .user-profile {
        border-radius: 5px 0 0 5px
    }

    .bg-c-lite-green {
        {% comment %} background: -webkit-gradient(linear, left top, right top, from(#001848), to(#001848));
        background: linear-gradient(to right, rgb(0, 24, 72), blue) {% endcomment %}
        background-color: #001848;
    }

    .user-profile {
        padding: 20px 0
    }

    .card-block {
        padding: 1.25rem
    }

    .m-b-25 {
        margin-bottom: 25px
    }

    .img-radius {
        border-radius: 100px
    }
    @media only screen and (min-width: 1400px) {
        .img-radius {
        border-radius: 100px
    }
    }
    h6 {
        font-size: 13px;
        font-family: 'Poppins', sans-serif;

    }

    .card .card-block p {
        line-height: 25px
    }

    @media only screen and (min-width: 1400px) {
        p {
            font-size: 14px
        }
    }

    .card-block {
        padding: 1.25rem
    }

    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }

    .m-b-20 {
        margin-bottom: 20px
    }

    .p-b-5 {
        padding-bottom: 5px !important
    }

    .card .card-block p {
        line-height: 25px
    }

    .m-b-10 {
        margin-bottom: 10px
    }

    .text-muted {
        color: #919aa3 !important
    }

    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }

    .f-w-600 {
        font-weight: 600
    }

    .m-b-20 {
        margin-bottom: 20px
    }

    .m-t-40 {
        margin-top: 20px
    }

    .p-b-5 {
        padding-bottom: 5px !important
    }

    .m-b-10 {
        margin-bottom: 10px
    }

    .m-t-40 {
        margin-top: 20px
    }

    .user-card-full .social-link li {
        display: inline-block
    }

    .user-card-full .social-link li a {
        font-size: 20px;
        margin: 0 10px 0 0;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out
    }
    </style>
</head>
<body>
    <div class="page-content page-container" id="page-content">
        <div class="padding">
            <div class="row  d-flex justify-content-center">
                <div class="col-xl-6 col-md-12 card p-4">
                    <div class=" user-card-full">
                        <div class="row m-l-0 m-r-0">
                            <div class="col-sm-4 bg-c-lite-green user-profile">
                                <div class="card-block text-center text-white">
                                    <div class="m-b-25"> <img src="{{ user.profile.image.url }}" class="img-radius img-fluid" alt="User-Profile-Image"> </div>
                                    <h6 class="f-w-600" style="font-size: 24px; color: black;"></h6>
                                    <p style="font-size: 14px; color: black;"></p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="card-block">
                                    </div>
                                    <form action="" method="POST" enctype="multipart/form-data">
                    
                                        {% csrf_token %}
                                        {{u_form|crispy}}
                                        {{p_form|crispy}}
                                        <button class="btn btn-success" id="logout-btn" type="submit">Update Profile</button>
                                    </form>
                                    <div style="margin-top: 10px;">
<!--                                            <button class="btn btn-success" id="logout-btn" type="submit">Update Profile</button>-->
                                        <button class="btn btn-secondary" id="logout-btn" type="submit"><a id="fa" href="{% url 'profile' %}" style="color: white; text-decoration: none;">Go Back</a></button>
                                    </div>
                                    <ul class="social-link list-unstyled m-t-40 m-b-10">
                                        <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook" data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook" aria-hidden="true"></i></a></li>
                                        <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter" data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter" aria-hidden="true"></i></a></li>
                                        <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="instagram" data-abc="true"><i class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        {% comment %} feather.replace() {% endcomment %}
      </script>
</body>
</html>

{% endblock prof_update %}

soac_users/templates/soac_users/register.html
{% extends 'base.html' %} {% load crispy_forms_tags %} 
{% block register %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div class="wrapper fadeInDown">
      <div id="formContent" class="pt-3">
        <h2 class="active">
          <a class="signin" href="" style="text-decoration: none">Sign Up</a>
        </h2>
        <h2 class="inactive underlineHover">
          <a class="signin" href="{% url 'login' %}" style="text-decoration: none">Sign In</a>
        </h2>
        <div class="fadeIn first"></div>

        <form action="" method="POST">
          {% csrf_token %} {{form|crispy}}
          <input type="submit" class="fadeIn fourth" value="Sign Up" />
        </form>

        <div id="formFooter">
          <p>
            Already have an account?
            <a class="underlineHover" href="{% url 'login' %}">Login </a>
          </p>
        </div>
      </div>
    </div>
  </body>
</html>
{% endblock register %}